name: Discord Message
description: Send a message to Discord
inputs:
  webhookUrl:
    description: "A Discord webhook URL"
    required: true
  message:
    description: "A message to send to Discord"
    required: true
runs:
  using: node20
  main: dist/index.js
