name: Discord Message
description: Send a message to Discord
branding:
  icon: message-square
  color: purple
inputs:
  webhookUrl:
    description: "A Discord webhook URL"
    required: true
  message:
    description: "A message to send to Discord"
    required: true
  username:
    description: "A username for the message"
  avatar:
    description: "An avatar for the message"
outputs:
  result:
    description: "An output for the message"
runs:
  using: node20
  main: dist/index.js
