name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: jackall3n/discord-message@v1.5
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Hello, from Github"
