name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4

      - name: Notify Discord
        uses: ./
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Hello, from Github"
